version: '3.9'
services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    restart: always
    container_name: seraph-next
    volumes:
          - .:/app
          - /app/node_modules
          - /app/.next
    env_file:
      - .env

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seraph
    restart: always
    container_name: seraph-db
    volumes:
      - ./data/db:/var/lib/postgresql/data